---
excludes:
  scopes:
    - pattern: "lint"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for static code analysis only."
    - pattern: "test"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for testing only."
    - pattern: "nox"
      reason: "TEST_DEPENDENCY_OF"
      comment: "Packages for testing only."
    - pattern: "doc"
      reason: "DOCUMENTATION_DEPENDENCY_OF"
      comment: "Packages for building the documentation only."
    - pattern: "eval"
      reason: "DEV_DEPENDENCY_OF"
      comment: "Packages for quality evaluation only."
license_choices:
  repository_license_choices:
    - given: FTL OR GPL-2.0-or-later
      choice: FTL
    - package_id: PyPI::python-dateutil:2.9.0.post0
      license_choices:
      - given: Apache-2.0 OR BSD License OR Dual License
        choice: BSD-3-Clause
resolutions:
  rule_violations:
    - message: ".*PyPI::omegaconf:2\\.3\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/omry/omegaconf/blob/master/LICENSE"
    - message: ".*PyPI::httpcore:1\\.0\\.9.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/encode/httpcore/blob/1.0.9/LICENSE.md"
    - message: ".*PyPI::emoji:2\\.12\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/carpedm20/emoji/blob/master/LICENSE.txt"
    - message: ".*PyPI::fsspec:2024\\.6\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/fsspec/filesystem_spec/blob/master/LICENSE"
    - message: ".*PyPI::ninja:1\\.11\\.1\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache-2.0 License: https://github.com/scikit-build/ninja-python-distributions/blob/1.11.1.1/LICENSE_Apache_20"
    - message: ".*PyPI::pandas:2\\.2\\.2.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/pandas-dev/pandas/blob/main/LICENSE"
    - message: ".*PyPI::pypdfium2:4\\.30\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD-3-Clause AND Apache-2.0"
    - message: ".*PyPI::httpx:0\\.27\\.2.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/encode/httpx/blob/0.12.1/LICENSE.md"
    - message: ".*PyPI::cycler:0\\.12\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/matplotlib/cycler/blob/v0.12.1/LICENSE"
    - message: ".*PyPI::tiktoken:0\\.7\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/openai/tiktoken/blob/0.7.0/LICENSE"
    - message: ".*PyPI::iopath:0\\.1\\.10.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/facebookresearch/iopath/blob/v0.1.10/LICENSE"
    - message: ".*PyPI::scipy:1\\.14\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/scipy/scipy/blob/v1.14.1/LICENSE.txt"
    - message: ".*PyPI::pypdf:5\\.3\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/py-pdf/pypdf/blob/5.3.0/LICENSE"
    - message: ".*PyPI::contourpy:1\\.3\\.0.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/contourpy/contourpy/blob/v1.3.0/LICENSE"
    - message: ".*PyPI::numpy:1\\.26\\.4.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/numpy/numpy/blob/v1.26.4/LICENSE.txt"
    - message: ".*PyPI::kiwisolver:1\\.4\\.7.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/nucleic/kiwi/blob/1.4.7/LICENSE"
    - message: ".*PyPI::pyinstrument:4\\.6\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/joerick/pyinstrument/blob/v4.6.1/LICENSE"
    - message: ".*PyPI::networkx:3\\.3.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/networkx/networkx/blob/main/LICENSE.txt"
    - message: ".*PyPI::jinja2:3\\.1\\.6.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "BSD 3-Clause License: https://github.com/pallets/jinja/blob/3.1.6/LICENSE.txt"
    - message: ".*PyPI::setuptools:80\\.7\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pypa/setuptools/blob/main/LICENSE"
    - message: ".*PyPI::docarray:0\\.39\\.1.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "Apache-2.0 https://github.com/docarray/docarray/blob/main/LICENSE.md"
    - message: ".*PyPI::pdfminer-six:20231228.*"
      reason: "CANT_FIX_EXCEPTION"
      comment: "MIT License: https://github.com/pdfminer/pdfminer.six/blob/20231228/LICENSE"
