name: Deploy development

on:
  workflow_dispatch:
  registry_package:

jobs:
  trigger:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event.registry_package.package_version.container_metadata.tag.name == 'development'
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment-name: "development"
            gitlab-project-id: "2549"
          - environment-name: "gcp-embedding-big"
            gitlab-project-id: "2335"
          - environment-name: "gcp-embedding-big-gpu"
            gitlab-project-id: "2464"
          - environment-name: "azure-embedding-big"
            gitlab-project-id: "2334"
          - environment-name: "azure-embedding-big-gpu"
            gitlab-project-id: "2463"
          - environment-name: "azure-description-big"
            gitlab-project-id: "2333"
          - environment-name: "azure-description-big-gpu"
            gitlab-project-id: "2465"
          - environment-name: "aws-embedding-big"
            gitlab-project-id: "2337"
          - environment-name: "aws-embedding-big-gpu"
            gitlab-project-id: "2461"

    name: Deploy to ${{ matrix.environment-name }}
    uses: epam/ai-dial-ci/.github/workflows/deploy-development.yml@2.3.1
    with:
      gitlab-project-id: ${{ matrix.gitlab-project-id }}
      environment-name: ${{ matrix.environment-name }}
    secrets:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_ACCESS_TOKEN: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
      DEPLOY_TRIGGER_TOKEN: ${{ secrets.DEPLOY_TRIGGER_TOKEN }}
