name: Release Workflow

on:
  push:
    branches: [development, release-*]

jobs:
  release:
    uses: epam/ai-dial-ci/.github/workflows/python_docker_release.yml@2.0.1
    secrets: inherit
    with:
      trivy-bypassed: true # HACK: Bypass trivy scan for now, WIP
